version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always

  redis:
    image: redis:7-alpine
    restart: always

  backend:
    image: pandarunquickly/qingtingzhe:backend-latest
    command: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:8000
    volumes:
      - ./PsychologyAnalysis:/app
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - BACKEND_CORS_ORIGINS_STR=${BACKEND_CORS_ORIGINS_STR}
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379/0
      - DASHSCOPE_API_KEY=${DASHSCOPE_API_KEY}
    depends_on:
      - db
      - redis
    restart: always

  worker:
    image: pandarunquickly/qingtingzhe:backend-latest
    command: python run_celery_worker.py
    volumes:
      - ./PsychologyAnalysis:/app
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379/0
      - DASHSCOPE_API_KEY=${DASHSCOPE_API_KEY}
    depends_on:
      - db
      - redis
    restart: always

  frontend:
    image: pandarunquickly/qingtingzhe:frontend-latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data: