"""Add status column to Assessment table

Revision ID: 269625ee49fe
Revises: 72143d5034d8
Create Date: 2025-04-25 23:48:19.299356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '269625ee49fe'
down_revision: Union[str, None] = '72143d5034d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('questionnaire_questions')
    op.add_column('analysis_data', sa.Column('status', sa.String(length=30), server_default='pending', nullable=False))
    op.create_index(op.f('ix_analysis_data_status'), 'analysis_data', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_data_status'), table_name='analysis_data')
    op.drop_column('analysis_data', 'status')
    op.create_table('questionnaire_questions',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('questionnaire_type', sa.TEXT(), nullable=False),
    sa.Column('question_number', sa.INTEGER(), nullable=False),
    sa.Column('question_text', sa.TEXT(), nullable=False),
    sa.Column('options', sa.TEXT(), nullable=False),
    sa.Column('scale_name', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('questionnaire_type', 'question_number')
    )
    # ### end Alembic commands ###
